baseurl = "https://joanca.github.io/"
languageCode = "es"
title = "joanca"
theme = "hemingway"
copyright = "&copy; Usando <a href=\"https://gohugo.io\">Hugo</a> con el tema <a href=\"https://github.com/tanksuzuki/hemingway\">Hemingway</a>."
disqusShortname = ""
googleAnalytics = ""

[params]

[params.highlight]
style = "github"
languages = ["python", "rust", "javascript"]

[[params.social]]
url = "https://github.com/joanca"
fa_icon = "fa-github"

[[params.social]]
url = "https://twitter.com/acsacsar"
fa_icon = "fa-twitter"

[[params.social]]
url = "/index.xml"
fa_icon = "fa-rss"
